import FreeCAD

doc = FreeCAD.ActiveDocument
objectSize = 20
textSize = 58
pageHeight = 297
cellSize = 60

def isLink(o):
  return o.TypeId == 'App::Link'

def isPart(o):
  return o.TypeId == 'PartDesign::Body'

def getRoot(o):
  root = o
  
  while isLink(root):
   root = root.LinkedObject
  
  return root

def getParts():
  parts = {}
  
  for o in FreeCAD.ActiveDocument.Objects:
    root = getRoot(o)
    
    if not isPart(root):
      continue
    
    if root in parts:
      parts[root] += 1
    else:
      parts[root] = 1
  
  return parts

def getDimensions(part):
  bb = part.Shape.BoundBox
  
  return (bb.XLength, bb.YLength, bb.ZLength)

def calculateScale(dimensions):
  biggestLength = max(dimensions)
  
  return objectSize / biggestLength

class BomPage:
  def __init__(self):
    template = doc.addObject('TechDraw::DrawSVGTemplate', 'BOMTemplate')
    template.Template = "C:/Meine Daten/programs/freecad/data/Mod/TechDraw/Templates/A4_Portrait_blank.svg"
    self.page = doc.addObject('TechDraw::DrawPage', 'BOM')
    self.page.Template = template
    self.column = 0
    self.row = 0
  
  def addView(self, partData):
    part = partData[0]
    count = partData[1]
    
    dimensions = getDimensions(part)
    view = self.createView(part, dimensions)
    cellDimensions = self.nextCellDimensions()
    self.alignView(view, cellDimensions)
    self.printInfo(part, cellDimensions, dimensions)
    self.printCount(part, count, cellDimensions)
  
  def createView(self, part, dimensions):
    view = doc.addObject('TechDraw::DrawViewPart', part.Label + '_View')
    self.page.addView(view)
    
    view.XSource = part
    view.Direction = FreeCAD.Vector(0.577,-0.577,0.577)
    view.XDirection = FreeCAD.Vector(1,0,0)
  
    view.ScaleType = u"Custom"
    view.Scale = calculateScale(dimensions)
    view.CoarseView = True
    view.Perspective = True
    
    view.ViewObject.LineWidth = '0.2 mm'
    
    view.recompute()

    return view
  
  def alignView(self, view, cellDimensions):
    view.X = '{} mm'.format(cellDimensions[0] - objectSize)
    view.Y = '{} mm'.format(cellDimensions[1] - objectSize / 2)
    
    view.recompute()
  
  def printInfo(self, part, cellDimensions, partDimensions):
    text = []
    
    if hasattr(part, 'Typ'):
      text.append(part.Typ)
    
    text.append('{} mm x {} mm x {} mm'.format(partDimensions[0], partDimensions[1], partDimensions[2]))

    if hasattr(part, 'Url'):
      text.append(part.Url)

    annotation = doc.addObject('TechDraw::DrawViewAnnotation', part.Label + '_Text')
    self.page.addView(annotation)

    annotation.TextSize = '3 mm'
    annotation.MaxWidth = '58 mm'
    annotation.X = '{} mm'.format(cellDimensions[0])
    annotation.Y = '{} mm'.format(cellDimensions[1] - objectSize - 10)
    annotation.Text = text
    
    doc.recompute()

  def printCount(self, part, count, cellDimensions):
    text = ['x {}'.format(count)]
    
    annotation = doc.addObject('TechDraw::DrawViewAnnotation', part.Label + '_Count')
    self.page.addView(annotation)

    annotation.TextSize = '5 mm'
    annotation.MaxWidth = '20 mm'
    annotation.X = '{} mm'.format(cellDimensions[0] + 20)
    annotation.Y = '{} mm'.format(cellDimensions[1] - objectSize / 2)
    annotation.Text = text
    
    doc.recompute()
  
  # (x, y)
  # x = Midpoint of the cell
  # y = top of the cell
  def nextCellDimensions(self):
    # 1. We want to have a 15mm offset from the edges of the page
    # 2. Each cell is 60 mm wide
    # 3. So the midpoint of the cell is the offset + the half cell width
    x = 15 + self.column * cellSize + cellSize / 2
    y = 297 - (15 + self.row * 60)
    
    self.nextColumnAndRow()
    
    return (x, y)

  def nextColumnAndRow(self):
    self.column += 1
    
    if self.column >= 3:
      self.column = 0
      self.row += 1

# Start of script
parts = getParts()
#sheet = FreeCAD.ActiveDocument.addObject('Spreadsheet::Sheet', 'Materialliste')
page = BomPage()

print(parts)

for partData in parts.items():
  page.addView(partData)

page.page.KeepUpdated = False
  
#  typ = part.Typ
#  url = part.Url